-- MySQL Script generated by MySQL Workbench
-- Sun Jun 13 17:22:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema serasa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS serasa ;

-- -----------------------------------------------------
-- Schema serasa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS serasa DEFAULT CHARACTER SET utf8 ;
USE serasa ;

-- -----------------------------------------------------
-- Table serasa.emprestimo
-- -----------------------------------------------------
DROP TABLE IF EXISTS serasa.emprestimo ;

CREATE TABLE IF NOT EXISTS serasa.emprestimo (
  id_emprestimo INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(1000) NOT NULL,
  descricao_html LONGTEXT NULL,
  juros_mes FLOAT NULL,
  valor_minimo FLOAT NULL,
  valor_maximo FLOAT NULL,
  parcela_minima INT NULL,
  parcela_maxima INT NULL,
  PRIMARY KEY (id_emprestimo))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table serasa.pessoas
-- -----------------------------------------------------
DROP TABLE IF EXISTS serasa.pessoas ;

CREATE TABLE IF NOT EXISTS serasa.pessoas (
  id_pessoas INT NOT NULL AUTO_INCREMENT,
  primeiro_nome VARCHAR(20) NULL,
  sobre_nome VARCHAR(1000) NULL,
  data_nascimento DATE NULL,
  sexo BINARY NULL,
  endereco TEXT NULL,
  PRIMARY KEY (id_pessoas))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table serasa.emprestimo_has_pessoas
-- -----------------------------------------------------
DROP TABLE IF EXISTS serasa.emprestimo_has_pessoas ;

CREATE TABLE IF NOT EXISTS serasa.emprestimo_has_pessoas (
  id_emprestimo INT NOT NULL,
  id_pessoas INT NOT NULL,
  data_hora DATETIME NULL,
  PRIMARY KEY (id_emprestimo, id_pessoas),
  CONSTRAINT fk_emprestimo_has_pessoas_emprestimo
    FOREIGN KEY (id_emprestimo)
    REFERENCES serasa.emprestimo (id_emprestimo)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_emprestimo_has_pessoas_pessoas1
    FOREIGN KEY (id_pessoas)
    REFERENCES serasa.pessoas (id_pessoas)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table serasa.emprestimo
-- -----------------------------------------------------
START TRANSACTION;
USE serasa;
INSERT INTO serasa.emprestimo (nome, descricao_html, juros_mes, valor_minimo, valor_maximo, parcela_minima, parcela_maxima) VALUES ('Empréstimo pessoal online', '<h4>O que é o empréstimo pessoal?</h4> <p> Também conhecido como “crédito pessoal”, é uma opção geralmente oferecida por bancos, fintechs e financeiras. A escolha mais indicada para diferentes necessidades, como: </p> <ul> <li>Pagamento de dívidas;</li> <li>Compras de alto valor</li> <li>Investimentos;</li> <li>Viagens;</li> <li>E muito mais!</li> </ul> <p> De maneira geral, você faz o seu pedido e escolhe a forma como vai usar o seu dinheiro. Importante: preste sempre atenção às taxas e condições de pagamento do seu empréstimo. </p> <p> No Serasa eCred, contamos com diversos parceiros que oferecem crédito e condições especiais para cada perfil financeiro. Aproveite essa oportunidade e solicite já. </p>', 3, 150, 30000, 6, 48);
INSERT INTO serasa.emprestimo (nome, descricao_html, juros_mes, valor_minimo, valor_maximo, parcela_minima, parcela_maxima) VALUES ('Empréstimo com garantia de imóvel', '<h4>Empréstimo com garantia de imóvel</h4> <p> A menor taxa de juros do mercado? Conheça o tipo de crédito que pode te garantir isso </p> <ul> <li>Use sua casa, apartamento, terrenos ou imóveis comerciais como garantia do seu empréstimo;</li> <li>Transforme até 60% do valor do seu imóvel em crédito para seu empréstimo;</li> <li>Os parceiros do Serasa eCred oferecem limites e serviços variados para cada perfil de consumidor, inclusive com opções sem anuidade.</li> <li>Com essa garantia, você consegue maiores prazos de pagamento e as menores taxas de juros do mercado;;</li> </ul>', 1.5, 3000, 150000, 12, 50);
INSERT INTO serasa.emprestimo (nome, descricao_html, juros_mes, valor_minimo, valor_maximo, parcela_minima, parcela_maxima) VALUES ('Empréstimo para autônomo', '<h4>Descubra como funciona e como solicitar esse tipo de crédito online</h4> <p> Empréstimo pessoal online pode ser uma grande ajuda para quem trabalha com carteira assinada e precisa de dinheiro rápido, sem burocracia e com baixa taxa de juros. </p> <p> E no caso de quem é autônomo? É possível conseguir? </p> <p> A resposta é SIM! Confira as nossas dicas de como solicitar um empréstimo para autônomo de uma maneira segura e digital. </p>', 2, 150, 30000, 6, 48);
INSERT INTO serasa.emprestimo (nome, descricao_html, juros_mes, valor_minimo, valor_maximo, parcela_minima, parcela_maxima) VALUES ('Empréstimo para negativado autônomo', '<h4>Empréstimo online para autônomo negativado, o que é?</h4> <p> Esse é um tipo de crédito oferecido para pessoas que possuem uma dívida em aberto, mas sem carteira assinada, a CLT. </p> <p> Quem é autônomo sabe que o dinheirinho no fim do mês nem sempre está garantido, por isso mesmo é muito importante contar com uma opção de empréstimo para cobrir seu orçamento ou para situações de emergência. </p> <p> É preciso lembrar, ainda, que esses profissionais podem ter mais dificuldade para comprovar renda. A análise de crédito, nesses casos, costuma ser um pouco mais exigente, contudo, isso não quer dizer que não dá para conseguir o empréstimo. </p> <p> É preciso lembrar, ainda, que esses profissionais podem ter mais dificuldade para comprovar renda. A análise de crédito, nesses casos, costuma ser um pouco mais exigente, contudo, isso não quer dizer que não dá para conseguir o empréstimo. </p>', 2.5, 150, 30000, 6, 48);
INSERT INTO serasa.emprestimo (nome, descricao_html, juros_mes, valor_minimo, valor_maximo, parcela_minima, parcela_maxima) VALUES ('Empréstimo sem comprovação de renda', '<h4>O que você precisa saber</h4> <p> Pesquisar e comparar opções de crédito ajudam a encontrar taxas de juros menores. </p> <p> A promessa de empréstimo sem comprovação de renda pode parecer tentadora para quem possui alguma restrição no nome. Mas nem sempre o fato de não precisar comprovar renda é uma alternativa interessante por causa dos juros. </p> <p> Para escolher a melhor opção de crédito para o seu bolso, você precisa pesquisar e comparar as ofertas do mercado. </p>', 2.48, 1000, 40000, 8, 48);
INSERT INTO serasa.emprestimo (nome, descricao_html, juros_mes, valor_minimo, valor_maximo, parcela_minima, parcela_maxima) VALUES ('Empréstimo para negativado', '<h4>Empréstimo para negativado, posso confiar?</h4> <p> Sim, pode confiar! Uma parte da população brasileira está negativada, o que na prática é aquela famosa expressão “Estar com o nome sujo”. Isso significa que uma pessoa tinha uma conta e não cumpriu com todos os pagamentos. Mas e aí, ainda dá para conseguir um empréstimo? </p> <p> É possível sim e algumas empresas são especializadas na linha de crédito para negativado, basta procurar direitinho. É importante lembrar, porém, que pode ser um pouco mais difícil achar opções com juros baixos se você possui alguma dívida. </p> <p> Quer comparar ofertas e escolher o melhor crédito para sua necessidade? Solicite já pelo Serasa eCred. </p>', 4, 150, 30000, 6, 48);
INSERT INTO serasa.emprestimo (nome, descricao_html, juros_mes, valor_minimo, valor_maximo, parcela_minima, parcela_maxima) VALUES ('Simulação de empréstimo e crédito', '<h4>O que é o simulador de crédito?</h4> <p> O simulador de crédito é um jeito eficaz de saber, antes de fechar um pedido de empréstimo, qual será o valor das suas parcelas, além de ter uma noção prévia sobre a média da taxa de juros cobrada em uma solicitação. </p> <p> Com o simulador do Serasa eCred, você pode comparar diferentes valores e prazos de pagamento para decidir qual é a melhor oferta para o seu bolso. Bem bacana, né? Dessa forma, você consegue se programar e fazer a escolha ideal. </p>', 3, 150, 30000, 6, 48);

COMMIT;


drop view if exists menu_emprestimo;

create view menu_emprestimo as
select group_concat(CONCAT( '<li><a href="emprestimo.php?id=', CONVERT(id_emprestimo, CHAR(3)), '">', nome, '</a></li>') SEPARATOR ' ' ) as resultado from emprestimo;

drop view if exists index_emprestimo;
create view index_emprestimo as select group_concat(CONCAT( '<div class="span3" style="margin-top: 30px;"><div class="item"><figure><div><img src="img/', CONVERT(id_emprestimo, CHAR(3)), '.png" alt="" style="height: 235px; width: 270px;"></div><figcaption><h3>', nome, '</h3><p><a href="emprestimo.php?id=', CONVERT(id_emprestimo, CHAR(3)), '"  title="',nome,' "><i class="icon-zoom-in icon-circled icon-bglight icon-2x active"></i></a></p></figcaption></figure></div></div>') SEPARATOR ' ' ) as resultado from emprestimo